FROM python:3.8.5-slim

WORKDIR /app

# Tools for installing packages
RUN pip install --no-cache-dir --upgrade pip pipenv

# Required packages installation layer (cached unless new dependencies are added)
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy --dev --ignore-pipfile && \
    pip uninstall --yes pipenv && \
    rm Pipfile Pipfile.lock

# Other files are copied via volumes on docker compose, but just in case...
COPY . ./
